
// these are custom defines...
#define kPopupIDOffset  10000

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Composer.rc
//

// IMPORTANT:  DO NOT EDIT THIS FILE WITH THE VISUAL C++ RESOURCE EDITOR, 
// YOU WILL TRASH THIS FILE!

#define MASTER_COLORS_BITMAP_PRO        100
#define MASTER_COLORS_BITMAP            101
#define WARN_HVC_BITMAP                 102
#define PALETTE_HEIGHT_DU               103
#define WARN_WEB_BITMAP                 103
#define WARN_CMYK_BITMAP                104
#define COMPOSER_LOGO_BITMAP            105
#define SORT_HVC                        106
#define SORT_HCV                        107
#define SORT_CHV                        108
#define SORT_CVH                        109
#define SORT_VCH                        110
#define SORT_VHC                        111
#define HELP_BITMAP                     112

#define IDC_CUSTOM_BUTTON               1000
#define IDC_HSB_H_TEXT                  1001
#define IDC_HSB_S_TEXT                  1002
#define IDC_HSB_B_TEXT                  1003
#define IDC_RGB_R_TEXT                  1004
#define IDC_RGB_B_TEXT                  1005
#define IDC_RGB_G_TEXT                  1006
#define IDC_LAB_L_TEXT                  1007
#define IDC_LAB_A_TEXT                  1008
#define IDC_LAB_B_TEXT                  1009
#define IDC_CMYK_C_TEXT                 1010
#define IDC_CMYK_M_TEXT                 1011
#define IDC_CMYK_Y_TEXT                 1012
#define IDC_CMYK_K_TEXT                 1013
#define IDC_HVC_H_TEXT                  1014
#define IDC_HVC_V_TEXT                  1015
#define IDC_HVC_C_TEXT                  1016
#define IDC_HVC_MUNSELL_H_TEXT          1017
#define IDC_HVC_MUNSELL_V_TEXT          1018
#define IDC_HVC_MUNSELL_C_TEXT          1019
#define IDC_HSB_H_RADIO                 1020
#define IDC_HSB_S_RADIO                 1021
#define IDC_HSB_B_RADIO                 1022
#define IDC_RGB_R_RADIO                 1023
#define IDC_RGB_G_RADIO                 1024
#define IDC_RGB_B_RADIO                 1025
#define IDC_LAB_L_RADIO                 1026
#define IDC_LAB_A_RADIO                 1027
#define IDC_LAB_B_RADIO                 1028
#define IDC_HVC_H_RADIO                 1029
#define IDC_HVC_V_RADIO                 1030
#define IDC_HVC_C_RADIO                 1031
#define IDC_CMYK_C_STATIC               1032
#define IDC_CMYK_M_STATIC               1033
#define IDC_CMYK_Y_STATIC               1034
#define IDC_CMYK_K_STATIC               1035
#define IDC_ONLY_WEB_CHECK              1036
#define IDC_COLOR_FLAG                  1037
#define IDC_HUE_SLIDER                  1038
#define IDC_COLORDISPLAY                1039
#define IDC_WARN_HVC_ICON               1040
#define IDC_WARN_HVC                    1041
#define IDC_WARN_CMYK_ICON              1042
#define IDC_WARN_CMYK                   1043
#define IDC_WARN_RGB_ICON               1044
#define IDC_WARN_RGB                    1045
#define IDC_QUICK_SWATCHES              1046
#define IDC_MUNSELL_CHECK               1047
#define IDC_HELP_BUTTON                 1048
#define IDC_MASTER_COLORS_LOGO          1049
#define IDC_PURCHASE_BUTTON             1050
#define IDC_CLICK_COUNT                 1051
#define IDC_CLICK_COUNT_STATIC          1052
#define IDC_SELECT_STATIC               1053
#define IDC_HSB_H_STATIC                1054
#define IDC_HSB_S_STATIC                1055
#define IDC_HSB_B_STATIC                1056
#define IDC_CMYK_C_LABEL                1057
#define IDC_CMYK_M_LABEL                1058
#define IDC_CMYK_Y_LABEL                1059
#define IDC_CMYK_K_LABEL                1060
#define IDC_HVC_H_STATIC                1061
#define IDC_HVC_V_STATIC                1062
#define IDC_HVC_C_STATIC                1063
#define IDC_RAW_COLOR_STATIC            1064
#define IDC_QUICK_SWATCHES_STATIC       1065

#define IDC_1ST_SEPARATOR               1066
#define IDC_1ST_TOGGLE                  1067

#if PROVERSION
	#define IDC_PROPORTION_STATIC           1068
	#define IDC_ACCURACY_STATIC             1069
	#define IDC_DEPTH_STATIC                1070

	#define IDC_CONTRAST_STATIC             1071
	#define IDC_PALETTE_SPLITSWATCH         1072
	#define IDC_CONTRAST                    1073

	#define IDC_RANGE_RADIO                 1074
	#define IDC_PROPORTION_RADIO            1075
	#define IDC_AUTO_RADIO                  1076

	#define IDC_ACCURACY_EDIT               1077
	#define IDC_DEPTH_EDIT                  1078
	#define IDC_CREATE_PALETTE_BUTTON       1079

	#define IDC_RANGE_STATIC                1080
	#define IDC_RANGE_COLOR_STATIC          1081
	#define IDC_RANGE_EDIT                  1082

	#define IDC_PROPORTION_COLOR1_STATIC    1083
	#define IDC_PROPORTION_COLOR2_STATIC    1084
	#define IDC_PROPORTION_EDIT             1085

	#define IDC_PALETTE_COLOR_1             1086
	#define IDC_PALETTE_COLOR_2             1087
	#define IDC_RANGE_COLOR                 IDC_PALETTE_COLOR_1  // MAKE SURE THIS IS THE SAME AS PALETTE_COLOR_1

	#define IDC_PALETTE_CONTROLS_FRAME      1088
	#define IDC_ACCURACY_FRAME              1089
	#define IDC_PROPORTION_FRAME            1090
	#define IDC_CONTRAST_FRAME				1091

	#define IDC_2ND_SEPARATOR               1092
	#define IDC_2ND_TOGGLE                  1093

	// palette section
	#define IDC_PALETTE_STATIC				1094
	#define IDC_PALETTE_ORDER_STATIC		1095
	
	#define IDC_SORT_HVC                    1096
	#define IDC_SORT_HCV                    1097
	#define IDC_SORT_CHV                    1098
	#define IDC_SORT_CVH                    1099
	#define IDC_SORT_VCH                    1100
	#define IDC_SORT_VHC                    1101

	#define IDC_PALETTE                     1102
	#define IDC_PALETTE_SCROLLBAR           1103
	#define IDC_SAVE_PALETTE_FRAME          1104
	#define IDC_SAVE_PALETTE_BUTTON         1105

	#define IDC_PALETTE_CONTRAST_LABEL	    1106
	#define IDC_PALETTE_CONTRAST		    1107

	#define IDC_PALETTE_SPLIT1_STATIC       1108
	#define IDC_PALETTE_SPLIT1              1109
	#define IDC_PALETTE_SPLIT2_STATIC       1110
	#define IDC_PALETTE_SPLIT2              1111
	#define IDC_PALETTE_CONTRAST1           1112
	#define IDC_PALETTE_CONTRAST2           1113

	#define IDC_RESULTS_FRAME               1114
	#define IDC_RESULTS_FRAME2              1115
	#define IDC_PALETTE_SORT_FRAME          1116
	
	#define IDC_PALETTE_RESULT				1117
	
	#define IDC_POPUP_SLIDER                1118

	#define IDC_RAW_COLOR_TEXT              1119
	
	#define IDC_DEPTH_EDIT_POPUP			(IDC_DEPTH_EDIT + kPopupIDOffset)
	#define IDC_PROPORTION_EDIT_POPUP		(IDC_PROPORTION_EDIT + kPopupIDOffset)
	#define IDC_ACCURACY_EDIT_POPUP			(IDC_ACCURACY_EDIT + kPopupIDOffset)
#else
	// standard version
	#define IDC_CONTRAST_STATIC             1068
	#define IDC_CONTRAST_STEPS_STATIC       1069
	#define IDC_PALETTE_SPLITSWATCH         1070
	#define IDC_CONTRAST                    1071
	#define IDC_CREATE_PALETTE_BUTTON       1072

	#define IDC_2ND_SEPARATOR               1073
	#define IDC_2ND_TOGGLE                  1074

	#define IDC_PALETTE                     1075
	#define IDC_PALETTE_SCROLLBAR           1076
	#define IDC_RAW_COLOR_TEXT              1077
#endif // PROVERSION



// custom dialog
#define IDC_PICKER                      1000
#define IDC_SELECTION                   1001
#define IDC_LIBRARY_POPUP               1002
#define IDC_COLOR_SLIDER                1003
#define IDC_COLOR_LIST                  1004
#define IDC_BOOK_LABEL                  1005
#define IDC_SEARCH_LABEL                1006


// the about dialog
#define IDC_GOTO_MASTER_COLORS          1080
#define IDC_COMPOSER_LOGO               1081
#define IDC_GOTO_PURCHASE               1082
#define IDC_DO_REGISTER                 1083
#define IDC_ENTER_OWNER_NAME            1084
#define IDC_ENTER_PURCHASE_CODE         1085
#define IDC_INSTRUCTIONS                1086
#define IDC_PURCHASE_CODE_LABEL         1087
#define IDC_OWNER_NAME_LABEL            1088
#define IDC_OWNER_NAME                  1089



#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         1
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
