/*
 *
 *	Copyright 2005 Master Colors.
 *
 *	This entire source code listing is the proprietary property of Master Colors
 *
 *	U.S. and Foreign patent applications pending
 *
 */

#ifndef Composer_Dialog_Indexes_h
#define Composer_Dialog_Indexes_h

#if WIN32
#include "Composer-sym.h"

enum 
{	
	PICKER_OK = 1, 
	PICKER_CANCEL, 
	
	PICKER_CUSTOM				= IDC_CUSTOM_BUTTON,
	
	// NOTE: this makes many assumptions about the order of the resource enums...
	HSB_HUE_TEXT				= IDC_HSB_H_TEXT,		
	HSB_SATURATION_TEXT, 
	HSB_BRIGHTNESS_TEXT,
	RGB_RED_TEXT, 
	RGB_GREEN_TEXT, 
	RGB_BLUE_TEXT,
	LAB_L_TEXT, 
	LAB_A_TEXT, 
	LAB_B_TEXT,
	CMYK_CYAN_TEXT,
	CMYK_MAGENTA_TEXT,
	CMYK_YELLOW_TEXT,
	CMYK_BLACK_TEXT,
	HVC_HUE_TEXT,
	HVC_VALUE_TEXT,
	HVC_CHROMA_TEXT,
	HVC_MUNSELL_HUE_TEXT,
	HVC_MUNSELL_VALUE_TEXT,
	HVC_MUNSELL_CHROMA_TEXT,
	
	HSB_HUE_RADIO,
	HSB_SATURATION_RADIO,
	HSB_BRIGHTNESS_RADIO,
	RGB_RED_RADIO,
	RGB_GREEN_RADIO,
	RGB_BLUE_RADIO,
	LAB_L_RADIO, 
	LAB_A_RADIO, 
	LAB_B_RADIO,
	HVC_HUE_RADIO,
	HVC_VALUE_RADIO,
	HVC_CHROMA_RADIO,

	CMYK_CYAN_TITLE,	
	CMYK_MAGENTA_TITLE, 
	CMYK_YELLOW_TITLE, 
	CMYK_BLACK_TITLE,

	ONLY_WEB_COLORS,	
	COLOR_FLAG,			
	HUE_SLIDER, 
	COLOR_DISPLAY,		

	// the code does stupid stuff here and adds one to the icon to get the color patch...
	// this means you cannot reorder the items without fixing the code!!!
	COLOR_SPACE_WARNING_ICON,	
	COLOR_SPACE_WARNING_COLOR,	
	PRINTABLE_WARNING_ICON,		
	PRINTABLE_WARNING_COLOR,	
	WEB_COLOR_WARNING_ICON,	
	WEB_COLOR_WARNING_COLOR,

	QUICK_SWATCHES,			
	MUNSELL_NOTATION,		
	HELP_BUTTON,			
	MASTER_COLORS_LOGO,

	REGISTER_BUTTON,		
	CLICK_COUNT,			
	CLICK_COUNT_LABEL,		

	SELECT_LABEL,			
	HSB_HUE_LABEL,			
	HSB_SATURATION_LABEL, 
	HSB_BRIGHTNESS_LABEL,
	CMYK_CYAN_LABEL,		
	CMYK_MAGENTA_LABEL, 
	CMYK_YELLOW_LABEL, 
	CMYK_BLACK_LABEL,
	HVC_HUE_LABEL,			
	HVC_VALUE_LABEL, 
	HVC_CHROMA_LABEL,
	RAW_COLOR_LABEL,		
	QUICK_SWATCHES_LABEL,	

	// toggle section
	FIRST_SEPARATOR_TOGGLE,	
	FIRST_SEPARATOR_BOUNDS,	

#if PROVERSION
	GENERATE_PROPORTION_LABEL,
	GENERATE_ACCURACY_LABEL, 
	GENERATE_DEPTH_LABEL,

	GENERATE_CONTRAST_LABEL,	
	GENERATE_SPLIT_SWATCH, 
	GENERATE_SPLIT_CONTRAST,
	
	GENERATE_RANGE_RADIO, 
	GENERATE_PROPORTION_RADIO, 
	GENERATE_AUTO_RANGE_RADIO,
	
	GENERATE_ACCURACY_TEXT, 
	GENERATE_DEPTH_TEXT, 
	GENERATE_CREATE_PALETTE_BUTTON,

	GENERATE_RANGE_LABEL,			// not in use
	GENERATE_RANGE_COLOR_LABEL,		// not in use
	GENERATE_RANGE_TEXT, 

	GENERATE_PROPORTION_FIRST_COLOR_LABEL, 
	GENERATE_PROPORTION_SECOND_COLOR_LABEL,
	GENERATE_PROPORTION_TEXT, 

	PALETTE_COLOR_1, 
	PALETTE_COLOR_2,

	PALETTE_CONTROLS_FRAME,
	ACCURACY_FRAME,
	PROPORTION_FRAME,
	CONTRAST_FRAME,
	
	// toggle section	
	SECOND_SEPARATOR_TOGGLE,
	SECOND_SEPARATOR_BOUNDS,

	// palette section
	PALETTE_LABEL, 
	PALETTE_ORDER_LABEL, 
	
	PALETTE_ORDER_0, 
	PALETTE_ORDER_1, 
	PALETTE_ORDER_2,
	PALETTE_ORDER_3, 
	PALETTE_ORDER_4, 
	PALETTE_ORDER_5,
	
	PALETTE_PALETTE, 
	PALETTE_SCROLL_BAR, 
	PALETTE_SAVE_FRAME,	// USED TO DETERMINE BOTTOM OF DIALOG
	PALETTE_SAVE_BUTTON,

	PALETTE_TYPE_STATIC,
	PALETTE_CONTRAST,

	PALETTE_SPLIT1_STATIC,
	PALETTE_SPLIT1,
	PALETTE_SPLIT2_STATIC,
	PALETTE_SPLIT2,
	PALETTE_CONTRAST1,
	PALETTE_CONTRAST2,

	RESULTS_FRAME,
	RESULTS_FRAME2,
	PALETTE_SORT_FRAME,
	
	PALETTE_RESULT,
	
	POPUP_SLIDER,

	RAW_COLOR_TEXT,
	
	POPUP_DEPTH      = IDC_DEPTH_EDIT_POPUP,
	POPUP_PROPORTION = IDC_PROPORTION_EDIT_POPUP,
	POPUP_ACCURACY   = IDC_ACCURACY_EDIT_POPUP,
#else
	// standard version
	GENERATE_CONTRAST_LABEL,	
	GENERATE_CONTRAST_STEPS_LABEL,
	GENERATE_SPLIT_SWATCH,		  
	GENERATE_SPLIT_CONTRAST,	
	GENERATE_CREATE_PALETTE_BUTTON,

	SECOND_SEPARATOR_TOGGLE,
	SECOND_SEPARATOR_BOUNDS,

	PALETTE_PALETTE,	
	PALETTE_SCROLL_BAR,	
	RAW_COLOR_TEXT
#endif
};
#else
// Mac version
// NOTE: this makes many assumptions about the order of the resource enums...
enum 
{	
	PICKER_OK 		= 1, 
	PICKER_CANCEL,			// 2 
	PICKER_CUSTOM,			// 3
	
	HSB_HUE_TEXT,			// 4
	HSB_SATURATION_TEXT, 	// 5
	HSB_BRIGHTNESS_TEXT,	// 6
	RGB_RED_TEXT, 			// 7
	RGB_GREEN_TEXT, 		// 8
	RGB_BLUE_TEXT,			// 9
	LAB_L_TEXT, 			// 10
	LAB_A_TEXT, 			// 11
	LAB_B_TEXT,				// 12
	CMYK_CYAN_TEXT,			// 13
	CMYK_MAGENTA_TEXT,		// 14
	CMYK_YELLOW_TEXT,		// 15
	CMYK_BLACK_TEXT,		// 16
	HVC_HUE_TEXT,			// 17
	HVC_VALUE_TEXT,			// 18
	HVC_CHROMA_TEXT,		// 19
	HVC_MUNSELL_HUE_TEXT,	// 20
	HVC_MUNSELL_VALUE_TEXT,	// 21
	HVC_MUNSELL_CHROMA_TEXT, // 22
	
	HSB_HUE_RADIO,			// 23
	HSB_SATURATION_RADIO,	// 24
	HSB_BRIGHTNESS_RADIO,	// 25
	RGB_RED_RADIO,			// 26
	RGB_GREEN_RADIO,		// 27
	RGB_BLUE_RADIO,			// 28
	LAB_L_RADIO, 			// 29
	LAB_A_RADIO, 			// 30
	LAB_B_RADIO,			// 31
	HVC_HUE_RADIO,			// 32
	HVC_VALUE_RADIO,		// 33
	HVC_CHROMA_RADIO,		// 34

	CMYK_CYAN_TITLE,		// 35
	CMYK_MAGENTA_TITLE, 	// 36
	CMYK_YELLOW_TITLE, 		// 37
	CMYK_BLACK_TITLE,		// 38

	ONLY_WEB_COLORS,		// 39
	COLOR_FLAG,				// 40
	HUE_SLIDER, 			// 41
	COLOR_DISPLAY,			// 42

	// the code does stupid stuff here and adds one to the icon to get the color patch...
	// this means you cannot reorder the items without fixing the code!!!
	COLOR_SPACE_WARNING_ICON,	// 43
	COLOR_SPACE_WARNING_COLOR,	// 44
	PRINTABLE_WARNING_ICON,		// 45
	PRINTABLE_WARNING_COLOR,	// 46
	WEB_COLOR_WARNING_ICON,		// 47
	WEB_COLOR_WARNING_COLOR,	// 48

	QUICK_SWATCHES,				// 49
	MUNSELL_NOTATION,			// 50
	HELP_BUTTON,				// 51
	MASTER_COLORS_LOGO,			// 52

	REGISTER_BUTTON,			// 53
	CLICK_COUNT,				// 54
	CLICK_COUNT_LABEL,			// 55

	SELECT_LABEL,				// 56
	HSB_HUE_LABEL,				// 57
	HSB_SATURATION_LABEL, 		// 58
	HSB_BRIGHTNESS_LABEL,		// 59
	CMYK_CYAN_LABEL,			// 60
	CMYK_MAGENTA_LABEL, 		// 61
	CMYK_YELLOW_LABEL, 			// 62
	CMYK_BLACK_LABEL,			// 63
	HVC_HUE_LABEL,				// 64
	HVC_VALUE_LABEL, 			// 65
	HVC_CHROMA_LABEL,			// 66
	RAW_COLOR_LABEL,			// 67
	QUICK_SWATCHES_LABEL,		// 68

	// toggle section
	FIRST_SEPARATOR_TOGGLE,		// 69
	FIRST_SEPARATOR_BOUNDS,		// 70

#if PROVERSION
	GENERATE_PROPORTION_LABEL,	// 71
	GENERATE_ACCURACY_LABEL, 	// 72
	GENERATE_DEPTH_LABEL,		// 73

	GENERATE_CONTRAST_LABEL,	// 74
	GENERATE_SPLIT_SWATCH, 		// 75
	GENERATE_SPLIT_CONTRAST,	// 76
	
	GENERATE_RANGE_RADIO, 		// 77
	GENERATE_PROPORTION_RADIO, 	// 78
	GENERATE_AUTO_RANGE_RADIO,	// 79
	
	GENERATE_ACCURACY_TEXT, 		// 80
	GENERATE_DEPTH_TEXT, 			// 81
	GENERATE_CREATE_PALETTE_BUTTON,	// 82

	GENERATE_RANGE_LABEL,			// 83 not in use
	GENERATE_RANGE_COLOR_LABEL,		// 84 not in use
	GENERATE_RANGE_TEXT, 			// 85

	GENERATE_PROPORTION_FIRST_COLOR_LABEL, 	// 86
	GENERATE_PROPORTION_SECOND_COLOR_LABEL,	// 87
	GENERATE_PROPORTION_TEXT, 				// 88

	PALETTE_COLOR_1, 			// 89
	PALETTE_COLOR_2,			// 90

	PALETTE_CONTROLS_FRAME,		// 91
	ACCURACY_FRAME,				// 92
	PROPORTION_FRAME,			// 93
	CONTRAST_FRAME,				// 94
	
	// toggle section	
	SECOND_SEPARATOR_TOGGLE,	// 95
	SECOND_SEPARATOR_BOUNDS,	// 96

	// palette section
	PALETTE_LABEL, 				// 97
	PALETTE_ORDER_LABEL, 		// 98
	
	PALETTE_ORDER_0, 			// 99
	PALETTE_ORDER_1, 			// 100
	PALETTE_ORDER_2,			// 101
	PALETTE_ORDER_3, 			// 102
	PALETTE_ORDER_4, 			// 103
	PALETTE_ORDER_5,			// 104
	
	PALETTE_PALETTE, 			// 105
	PALETTE_SCROLL_BAR, 		// 106
	PALETTE_SAVE_FRAME,			// 107 USED TO DETERMINE BOTTOM OF DIALOG
	PALETTE_SAVE_BUTTON,		// 108

	PALETTE_TYPE_STATIC,		// 109
	PALETTE_CONTRAST,			// 110

	PALETTE_SPLIT1_STATIC,		// 111
	PALETTE_SPLIT1,				// 112
	PALETTE_SPLIT2,				// 113
	PALETTE_CONTRAST1,			// 114
	PALETTE_CONTRAST2,			// 115
	
	RESULTS_FRAME,				// 116
	RESULTS_FRAME2,				// 117
	PALETTE_SORT_FRAME,			// 118

	PALETTE_RESULT,		// 119
	
	POPUP_SLIDER,		// 120

	RAW_COLOR_TEXT,		// 121
	
	POPUP_DEPTH,		// 122
	POPUP_PROPORTION,	// 123
	POPUP_ACCURACY		// 124
#else
	// standard version
	GENERATE_CONTRAST_LABEL,		// 71
	GENERATE_CONTRAST_STEPS_LABEL,	// 72
	GENERATE_SPLIT_SWATCH,		  	// 73
	GENERATE_SPLIT_CONTRAST,		// 74
	GENERATE_CREATE_PALETTE_BUTTON,	// 75

	SECOND_SEPARATOR_TOGGLE,		// 76
	SECOND_SEPARATOR_BOUNDS,		// 77

	PALETTE_PALETTE,				// 78
	PALETTE_SCROLL_BAR,				// 79
	RAW_COLOR_TEXT					// 80
#endif
};

#endif

// Group ranges
enum 
{	
	COLOR_COMPONENT_TEXT_START = HSB_HUE_TEXT, 
	COLOR_COMPONENT_TEXT_END = HVC_CHROMA_TEXT,

	COLOR_COMPONENT_RADIO_START = HSB_HUE_RADIO,
	COLOR_COMPONENT_RADIO_END = HVC_CHROMA_RADIO,


#if PROVERSION	
	GENERATE_START = GENERATE_PROPORTION_LABEL,
	GENERATE_END = CONTRAST_FRAME,

	PALETTE_START = SECOND_SEPARATOR_TOGGLE, 
	PALETTE_END = PALETTE_SORT_FRAME
#else
	GENERATE_START = GENERATE_CONTRAST_LABEL,
	GENERATE_END = GENERATE_CREATE_PALETTE_BUTTON,

	PALETTE_START = SECOND_SEPARATOR_TOGGLE, 
	PALETTE_END = PALETTE_SCROLL_BAR
#endif
};



typedef enum
{
	kUpdateUnspecifiedFlag		= 0,
	kUpdateFromQuickColorFlag	= 1 << 0,
	kUpdateFromPaletteFlag		= 1 << 1
} SelectionFlags;



#endif	// !Composer_Dialog_Indexes_h

// EOF
